export const translate = {
  APP_NAME: "Reflektor",
  VALIDATION_PASSWORD_NOT_SAME: "Lozinke su različite",
  VALIDATION_PASSWORD_MIN_LENGTH: "Minimum 4 karaktera",
  VALIDATION_REQUIRED_FIELD: "Obavezno polje",
  VALIDATION_MAX_VALUE: "Maksimalna vrednost je {max}",
  VALIDATION_MIN_VALUE: "Minimalna vrednost je {min}",
  VALIDATION_NOT_EMPTY: "Polje može biti prazno",
  VALIDATION_ONLY_NUMBERS: "Samo brojevi",
  VALIDATION_REGEX: "Regex nije prošla",
  VALIDATION_NOT_SAME: "Polja se moraju podudarati",
  VALIDATION_USER_PASSWORD_MIN_LENGTH: "Lozinka mora biti najmanje 4 karaktera",
  VALIDATION_USER_PASSWORD_CUSTOM_VALIDATION: 'Lozinka mora imati bar jedan karakter',
  VALIDATION_USER_PASSWORD_CUSTOM_VALIDATION_MIN_NUMBER: 'Lozinka mora imati bar jedan broj',
  VALIDATION_USER_PASSWORD_CUSTOM_VALIDATION_MIN_UPPER_CASE: 'Lozinka mora imati bar jedno veliko slovo',

  LOGIN_FORM_TITLE: "Prijava",
  USERNAME_LABEL: "Korisničko ime",
  USERNAME_HELPER_TEXT: "unesite korisničko ime",
  PASSWORD_LABEL: "Lozinka",
  PASSWORD_HELPER_TEXT: "unesite lozinku",
  LOGIN_FORM_BUTTON_LABEL: "Prijava",
  BUTTON_ACTION_BUTTON_SUBMIT_LABEL: "Sačuvaj",
  BUTTON_ACTION_BUTTON_CANCEL_LABEL: "Poništi",
  BUTTON_ACTION_BUTTON_UPDATE_LABEL: "Izmeni",
  BUTTON_OK_LABEL: "U redu",
  BUTTON_CANCEL_LABEL: "Poništi",

  DIALOG_INFO_TITLE: "Info",

  SAVE_LABEL: "Sačuvaj",
  EDIT_LABEL: "Izmeni",
  DELETE_LABEL: "Briši",
  RESET_LABEL: "Reset",

  USERS_PAGE_TITLE: "Korisnici",
  CATEGORY_PAGE_TITLE: "Kategorije",
  ARTICLES_PAGE_TITLE: "Članci",

  USER_DASHBOARD_TAB_INFO_LABEL: "Info",
  USER_DASHBOARD_TAB_MY_PROFILE_LABEL: "Moj Profil",
  USER_DASHBOARD_SEARCH_INPUT_HELPER_TEXT: "Pretražite po korisničkom imenu, e-adresi",
  USER_DASHBOARD_SEARCH_TOTAL_COUNT_LABEL: "UKUPNO",

  USER_INFO_TITLE: "OPŠTI DETALJI",
  USER_INFO_EMAIL_LABEL: "E-adresa",
  USER_INFO_NICKNAME_LABEL: "Nadimak",
  USER_INFO_USERNAME_LABEL: "Korisničko",

  USER_FORM_NEW_TITLE: "Dodaj korisnika",
  USER_FORM_EDIT_TITLE: "Izmeni korisnika",
  USER_FORM_USERNAME_LABEL: "Korisničko ime",
  USER_FROM_USERNAME_HELPER_TEXT: "unesite korisničko ime",
  USER_FORM_EMAIL_LABEL: "E-adresa",
  USER_FORM_EMAIL_HELPER_TEXT: "unesite e-adresu",
  USER_FORM_NICKNAME_LABEL: "Nadimak",
  USER_FORM_NICKNAME_HELPER_TEXT: "unesite nadimak",
  USER_FORM_DESCRIPTION_LABEL: "Opis",
  USER_FORM_DESCRIPTION_HELPER_TEXT: "unesite opis",
  USER_FORM_PASSWORD_LABEL: "Lozinka",
  USER_FORM_PASSWORD_HELPER_TEXT: "unesi novu lozinku",
  USER_FORM_CONFIRM_PASSWORD_LABEL: "Ponovi lozinku",
  USER_FORM_CONFIRM_PASSWORD_HELPER_TEXT: "unesi ponovi lozinku",
  USER_FORM_CHANGE_PASSWORD_LABEL: "Promeni lozinku",

  USER_FORM_RESET_PASSWORD_TITLE: "Reset lozinke",
  USER_FORM_RESET_PASSWORD_TEXT: "Da li ste sigurni da resetujete lozinku?",

  USER_CHANGE_PASSWORD_TITLE: "Promena lozinke",
  USER_CHANGE_PASSWORD_CURRENT_PASSWORD_LABEL: "Lozinka",
  USER_CHANGE_PASSWORD_CURRENT_PASSWORD_HELPER_TEXT: "unesi lozinku",
  USER_CHANGE_PASSWORD_NEW_PASSWORD_LABEL: "Nova lozinka",
  USER_CHANGE_PASSWORD_NEW_PASSWORD_HELPER_TEXT: "unesi novu lozinku",
  USER_CHANGE_PASSWORD_CONFIRM_PASSWORD_LABEL: "Ponovi lozinku",
  USER_CHANGE_PASSWORD_CONFIRM_PASSWORD_HELPER_TEXT: "unesi ponovi lozinku",
  USER_FORM_REMOVE_TEXT: "Da li ste sigurni da obrišete korisnika-a?",
  USER_FORM_REMOVE_TITLE: "Brisanje korisnika",

  USER_FORM_RESET_PASSWORD_BUTTON_LABEL: "Reset",

  MY_PROFILE_TITLE_LABEL: "Informacije o profilu",

  ARTICLES_DASHBOARD_SEARCH_INPUT_HELPER_TEXT: "pretražite po",
  ARTICLE_HEADER_LABEL: "Naslov",
  ARTICLE_BUTTON_NEW_LABEL: "Novi",
  ARTICLE_BUTTON_EDIT_LABEL: "Izmeni",
  ARTICLE_BUTTON_DELETE_LABEL: "Briši",
  ARTICLE_FORM_EDIT_TITLE_LABEL: "Izmena artikla",
  ARTICLE_FORM_ADD_TITLE_LABEL: "Kreiranje artikla",
  ARTICLE_FORM_BUTTON_BACK_LABEL: "Nazad",
  ARTICLE_FORM_SELECT_CATEGORY_LABEL: "Kategorija",
  ARTICLE_FORM_SELECT_CATEGORY_HELPER_TEXT: "unesite kategoriju",
  ARTICLE_FORM_INPUT_HEADER_LABEL: "Naslov",
  ARTICLE_FORM_INPUT_HEADER_HELPER_TEXT: "unesite naslov",
  ARTICLE_FORM_INPUT_USE_LINK_LABEL: "Koristi link",
  ARTICLE_FORM_INPUT_LINK_LABEL: "Link",
  ARTICLE_FORM_INPUT_LINK_HELPER_TEXT: "unesite link",
  ARTICLE_FORM_INPUT_CONTENT_LABEL: "Unesite tekst",
  ARTICLE_FORM_INPUT_IMAGE_LABEL: "Izaberite sliku",
  ARTICLE_FORM_DRAG_AND_DROP_TEXT: "Ubacite ili izaberite sliku",
  ARTICLE_FORM_DRAG_AND_DROP_ALT_TEXT: "Slika članka",
  CATEGORY_FORM_TITLE_EDIT: "Izmeni kategoriju",
  CATEGORY_FORM_TITLE_DEFINE: "Dodaj kategoriju",
  CATEGORY_FORM_INPUT_NAME_LABEL: "Naziv",
  CATEGORY_FORM_INPUT_NAME_HELPER_TEXT: "unesite naziv",
  CATEGORY_FORM_INPUT_DESCRIPTION_LABEL: "Opis",
  CATEGORY_FORM_INPUT_DESCRIPTION_HELPER_TEXT: "unesite opis",
  ARTICLE_INFO_IMAGE_LABEL: "Slika",
  ARTICLE_INFO_HEADER_LABEL: "Naslov",
  ARTICLE_INFO_LINK_LABEL: "Link",
  ARTICLE_INFO_CONTENT_LABEL: "Tekst",
  ARTICLE_INFO_CATEGORY_LABEL: "Kategorija",
  ARTICLE_FORM_REMOVE_TEXT: "Da li ste sigurni da obrišete članak?",
  ARTICLE_FORM_REMOVE_TITLE: "Brisanje članka",

  /** success messages */
  USER_SUCCESS_INSERTED_TEXT: "Uspešno kreiran editor",
  USER_SUCCESS_CHANGED_PASSWORD_TEXT: "Uspešno izmenjena lozinka",
  USER_SUCCESS_UPDATED_TEXT: "Uspešno izmenjen editor",
  USER_SUCCESS_DELETED_TEXT: "Uspešno obrisan editor",
  ARTICLE_SUCCESS_INSERTED_TEXT: "Uspešno kreiran članak",
  ARTICLE_SUCCESS_UPDATED_TEXT: "Uspešno izmenjen članak",
  ARTICLE_SUCCESS_DELETED_TEXT: "Uspešno obrisan članak",
  CATEGORY_SUCCESS_CREATED_TEXT: "Uspešno kreairana kategorija",

};